export const decks = [
  { type: "Questão", question: "Sou comprida e sou amarela. Quem sou eu?", answer: "Banana" },
  { type: "Questão", question: "Posso ser verde, vermelha ou amarela. Quem sou eu?", answer: "Maçã" },
  { type: "Questão", question: "Verde por fora e vermelha por dentro. Quem sou eu?", answer: "Melancia" },
  { type: "Questão", question: "Andamos sempre lado a lado, somos vermelhas e com um caroço no meio. Quem somos nós?", answer: "Cerejas" },
  { type: "Questão", question: "Tenho uma coroa na minha cabeça. Quem sou eu?", answer: "Ananás" },
  { type: "Questão", question: "Sou a irmã mais nova da laranja. Quem sou eu?", answer: "Tangerina" },
  { type: "Questão", question: "Tenho pelinho por fora e sou verde e amarelo por dentro. Quem sou eu?", answer: "Kiwi" },
  { type: "Questão", question: "Posso ser macio ou até mesmo áspero, mas tenho sempre um grande caroço castanho por dentro. Quem sou eu?", answer: "Pêssego" },
  { type: "Questão", question: "Sou muitas vezes confundido com um legume. Quem sou eu?", answer: "Tomate" },
  { type: "Questão", question: "Tenho um escudo de espinhos. Quem sou eu?", answer: "Castanha" },
  { type: "Questão", question: "Tenho o mesmo nome que aquilo que te aquece os braços. Quem sou eu?", answer: "Manga" },
  { type: "Questão", question: "Sou a prima mais curvinha da maçã. Quem sou eu?", answer: "Pêra" },
  { type: "Questão", question: "Tenho um caroço e posso ser roxa ou amarela. Quem sou eu?", answer: "A resposta não foi fornecida" },
  { type: "Questão", question: "Sou pequenino, gordinho e azulinho. Quem sou eu?", answer: "Mirtilos" },
  { type: "Questão", question: "Sou a irmã vermelha da amora. Quem sou eu?", answer: "Framboesa" },
  { type: "Questão", question: "Venho de um arbusto com muitos picos, mas a minha cor vermelha dá nas vistas. Quem sou eu?", answer: "Amora" },
  { type: "Questão", question: "Sou a mulher do melão. Quem sou eu?", answer: "Meloa" },
  { type: "Questão", question: "Sou roxo por fora e com muitos pedacinhos pretos e verdes por dentro. Quem sou eu?", answer: "Maracujá" },
  { type: "Questão", question: "Tens que me partir ao meio e comer com uma colher. Quem sou eu?", answer: "Maracujá" },
  { type: "Questão", question: "Quando sou novo tenho uma casca roxa muito lisinha, mas quando envelheço fico com muitas rugas. Quem sou eu?", answer: "Maracujá" },
  { type: "Questão", question: "Sou a fruta preferida dos macacos. Quem sou eu?", answer: "Banana" },
  { type: "Questão", question: "Sou sumarenta por dentro e posso ter muitas cores. Quem sou eu?", answer: "Maçã" },
  { type: "Questão", question: "Apesar de ser redondinho e bem branquinho, gostam de me comer às fatias. Quem sou eu?", answer: "Melão" },
  { type: "Questão", question: "Sou colhida em forma de cacho, juntamente com as minhas irmãs. Quem sou eu?", answer: "Uva" },
  { type: "Questão", question: "Posso ser roxa ou verdinha e nunca estou sozinha. Quem sou eu?", answer: "Uva" },
  { type: "Questão", question: "Sou confundida com a tangerina. Quem sou eu?", answer: "Laranja" },
  { type: "Questão", question: "Sou vermelha por dentro e por fora. Quem sou eu?", answer: "Romã" },
  { type: "Questão", question: "Sou uma bola dura muito gigante e a minha cor característica é o vermelho. Quem sou eu?", answer: "Romã" },
  { type: "Questão", question: "A minha casca é cor de laranja e sou fácil de descascar. Quem sou eu?", answer: "Laranja" },
  { type: "Questão", question: "Sou pequena, redonda e tenho uma casca fina. Conseguem fazer de mim sumo, uma tarde ou também podem comer à dentada. Quem sou eu?", answer: "Maçã" },
  { type: "Questão", question: "Tenho um rabo mais largo mas uma cintura fina. Quem sou eu?", answer: "Pêra" },
  { type: "Questão", question: "Sou um verde claro por fora, cor de laranja por dentro e sou uma bola redonda. Quem sou eu?", answer: "Meloa" },
  { type: "Questão", question: "Sou bem amarelo por dentro e tenho umas enormes folhas no meu topo. Quem sou eu?", answer: "Ananás" },
  { type: "Questão", question: "Sou pequeno, vermelho e com muitas pintinhas e fico excelente nos iogurtes. Quem sou eu?", answer: "Morango" },
  { type: "Questão", question: "Podes comer sozinho, com chantilly ou até mesmo com chocolate. Quem sou eu?", answer: "Morango" },
  { type: "Questão", question: "Sou refrescante, tropical e podes comer à colherada ou em cubinhos. Quem sou eu?", answer: "Manga" },
  { type: "Questão", question: "Tenho muitas sementinhas para comeres até lamber os lábios. Quem sou eu?", answer: "Maracujá" },
  { type: "Questão", question: "Tenho uma casca maleável e amarela por fora, mas sou branquinha por dentro. Quem sou eu?", answer: "Banana" },
  { type: "Questão", question: "Sou parecida com o melão, mas sou mais refrescante e com cores mais divertidas. Quem sou eu?", answer: "Melancia" },
  { type: "Questão", question: "Qual destas frutas tem mais água? Melancia, Pêssego ou Mirtilos?", answer: "Melancia" },
  { type: "Questão", question: "Qual a planta de onde cresce a banana?", answer: "Bananeira" },
  { type: "Questão", question: "A manga tem caroço?", answer: "Sim" },
  { type: "Questão", question: "Os morangos crescem em plantas muito altas ou baixas?", answer: "Baixas" },
  { type: "Questão", question: "A romã tem casca mole ou casca dura?", answer: "Dura" },
  { type: "Questão", question: "Pode-se comer a casca da maçã?", answer: "Sim" },
  { type: "Questão", question: "Pode-se comer a casca da laranja?", answer: "Não" },
  { type: "Questão", question: "Só podemos comer fruta à sobremesa?", answer: "Não! podemos comer durante a refeição, ao lanche e ao pequeno almoço!" },
  { type: "Questão", question: "Qual destas frutas é mais comum no verão? Cereja, maçã ou banana?", answer: "Cereja" },
  { type: "Questão", question: "Qual destas frutas não é costume do verão? Melancia, morangos ou tangerina?", answer: "Tangerina" },
  { type: "Questão", question: "A laranja é uma fruta de inverno ou de verão?", answer: "Inverno" },
  { type: "Curiosidade", tema: "Sabias que as uvas não crescem sozinhas, elas crescem em cachos, como uma \"família de frutinhas\" que ficam todas juntinhas e tu podes comer a casca da uva. Ela é fininha e ajuda a proteger a frutinha?" },
  { type: "Curiosidade", tema: "Sabias que se espremerem uma laranja, sai um sumo delicioso! Este sumo tem vitamina C, que ajuda a deixar as pessoas fortes e saudáveis?" },
  { type: "Curiosidade", tema: "Sabias que a banana vem com sua própria \"embalagem\"? A casca protege a fruta por dentro e é fácil de descascar! Além disso, macacos adoram comer bananas?" },
  { type: "Curiosidade", tema: "Sabias que a melancia é feita de muita água? É por isso que ela é tão refrescante para comer em dias quentes?" },
  { type: "Curiosidade", tema: "Sabias que o ananás por fora é cheio de espinhos, mas por dentro é doce e suculento? O ananás é como uma fruta que usa \"armadura\" para se proteger!" },
  { type: "Curiosidade", tema: "Sabias que os cocos crescem em palmeiras e, por dentro, têm água, que é refrescante para beber. Eles são como \"copinhos\" que a natureza faz!" },
  { type: "Curiosidade", tema: "Sabias que a romã é uma fruta cheia de sementinhas vermelhas brilhantes que parecem pequenas joias. Cada sementinha tem um suminho doce?" },
  { type: "Curiosidade", tema: "Sabias que a framboesa é parecida com a amora, mas normalmente é vermelha ou rosa. É macia e formada por muitas \"bolinhas\" pequeninas, e quando está madura, cai facilmente do galho?" },
  { type: "Curiosidade", tema: "Sabias que a casca da banana é escorregadia devido à sua grande quantidade de água?" },
  { type: "Curiosidade", tema: "Sabias que existem mais de 1000 bananas diferentes?" },
  { type: "Curiosidade", tema: "Sabias que as maçãs flutuam na água? Isso acontece porque têm ar, fazendo com que ela flutue como um barquinho?" },
  { type: "Curiosidade", tema: "Sabias que almofadas de sementes secas de cerejas ajudam a diminuir as dores de cabeça?" },
  { type: "Curiosidade", tema: "Sabias que antigamente, as pessoas usavam morangos para limpar os dentes?" },
  { type: "Curiosidade", tema: "Sabias que existem frutas em todas as cores? As frutas vêm em muitas cores diferentes, como vermelho, amarelo, verde, roxo e até laranja. Isso ajuda a tornar as refeições mais coloridas e divertidas!" },
  { type: "Curiosidade", tema: "Sabias que as pêras além de serem consumidas frescas, também são usadas em muitas outras receitas? Como tarte, compotas e até pratos salgados, como saladas." },
  { type: "Curiosidade", tema: "Sabias que o limão pode acender uma lâmpada?" },
  { type: "Curiosidade", tema: "Sabias que o cheiro das bananas faz as maçãs amadurecerem mais depressa?" },
  { type: "Curiosidade", tema: "Sabias que o limão pode brilhar no escuro? Basta esfregarmos um pouco de sal no sumo de limão e depois apontar uma luz ultravioleta." },
  { type: "Curiosidade", tema: "Sabias que as bananas também podem ser vermelhas?" },
  { type: "Curiosidade", tema: "Sabias que os mirtilos podem ser usados para fazer tintas naturais para tecidos?" },
  { type: "Curiosidade", tema: "Sabias que existem melancias quadradas no Japão?" },
  { type: "Curiosidade", tema: "Sabias que em climas muito quentes, a casca da laranja pode ficar verde e não laranja?" },
  { type: "Curiosidade", tema: "Sabias que a laranja tem um \"sorriso\" ao ser cortada? Quando cortas uma laranja ao meio, ela parece ter um sorriso com as suas fatias!" },
  { type: "Curiosidade", tema: "Sabias que o figo é uma fruta \"invertida\"? A parte que comemos é na verdade a flor do figo, que cresce no interior da fruta. É muito diferente de outras frutas!" },
  { type: "Curiosidade", tema: "Sabias que o morango é uma das poucas frutas que não crescem em árvores? Ele cresce em plantas que podem ser encontradas perto do chão, onde é mais fácil de apanhar!" },
  { type: "Curiosidade", tema: "Sabias que as frutas podem ser cultivadas em casa? Muitas frutas, como morangos e tomates, podem ser cultivadas em vasos em casa, tornando-se uma atividade divertida para toda a família!" },
  { type: "Curiosidade", tema: "Sabias que as frutas podem ajudar a fazer gelados? Muitas frutas, como morangos e mangas, podem ser transformadas em gelados fresquinhos, deliciosos para o verão!" },
  { type: "Curiosidade", tema: "Sabias que as frutas também podem ser secas? Quando secas, como os figos secos ou as passas, elas ficam mais doces e podem ser usadas em bolos e cereais!" },
  { type: "Curiosidade", tema: "Sabias que o pêssego é uma fruta de verão? Esta fruta é mais popular durante o verão, pois é suculenta e refrescante, perfeita para os dias quentes." },
  { type: "Curiosidade", tema: "Sabias que a fruta mais famosa do mundo é a banana?" }
];